name: Arduino Library Checks
on: 
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
jobs:
  ArduinoLintjob:
    name: Run Arduino Lint
    env:
      compliance: strict
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1


